apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gitops-kong
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - udpingresses.configuration.konghq.com
  - kongclusterplugins.configuration.konghq.com
  - kongconsumers.configuration.konghq.com
  - kongplugins.configuration.konghq.com
  - kongingresses.configuration.konghq.com
  - tcpingresses.configuration.konghq.com
  verbs:
  - create
  - patch
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: gitops-kong-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-kong
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops