apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    metadata:
      name: vault-secret
    spec:
      serviceAccountName: vault-init
      containers:
      - image: registry.access.redhat.com/ubi8:8.6-855
        name: vault-secret
        command:
        - /bin/sh
        - -c
        - |
          echo "Enable and configure Kubernetes auth"
          oc exec vault-0 -- vault login -no-print $(cat $KEYS | jq -r '.root_token')
          oc exec vault-0 -- vault auth enable kubernetes
          oc exec vault-0 -- vault write auth/kubernetes/config \
            issuer="https://kubernetes.default.svc.cluster.local" \
            token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
            kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
            kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          echo "Enable KV v2 secret engine"
          oc exec vault-0 -- vault secrets enable -path=avp -version=2 kv
          echo "Create secret"
          oc exec vault-0 -- vault kv put avp/kong-enterprise-license license=FAKE_LICENSE
          echo "Create policy"
          oc exec vault-0 -- wget -O /tmp/argocd-repo-server-policy.hcl https://raw.githubusercontent.com/vbelouso/kong-discovery-casey/vault-ha/vault/argocd/postinstall/argocd-repo-server-policy.hcl && \
            vault policy write argocd-repo-server /tmp/argocd-repo-server-policy.hcl
          oc exec vault-0 -- vault write auth/kubernetes/role/argocd-repo-server \
            bound_service_account_names=argocd-repo-server \
            bound_service_account_namespaces=openshift-gitops policies=argocd-repo-server
          sleep infinity
      restartPolicy: Never

