apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
spec:
  destination:
    namespace: kong
    server: "https://kubernetes.default.svc"
  source:
    path: vault/argocd/kong
    repoURL: "https://github.com/vbelouso/kong-discovery-casey.git"
    targetRevision: vault-ha
    plugin:
      name: argocd-vault-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
