apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-prereqs
spec:
  project: default
  source:
    repoURL: "https://github.com/vbelouso/kong-discovery-casey.git"
    path: vault/argocd/prereqs
    targetRevision: vault-ha
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
