apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: consul
    server: "https://kubernetes.default.svc"
  source:
    path: vault/charts/consul
    repoURL: "https://github.com/vbelouso/kong-discovery-casey.git"
    targetRevision: vault-ha
    helm:
      valueFiles:
        - values-custom.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
