apiVersion: v1
kind: Namespace
metadata:
  name: consul
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops