kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-custom
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-custom-binding
subjects:
  - kind: ServiceAccount
    name: redhat-kong-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-custom
